Handle non-UTF-8 exceptions
efabless/openlane2 pull request #385
Opened 2024-02-12 18:21 UTC by donn

* `openlane.steps.Step`
  * Fixed `run_subprocess` crashing upon a tool outputting gibberish - a `StepException` is raised now

---

Fixes #226

2024-02-12 19:03 UTC, kareefardi requested changes

2024-02-12 19:03 UTC, kareefardi commented on openlane/steps/step.py
> +        print(cmd_str, kwargs)
debugging vestige?

2024-02-12 22:37 UTC, donn commented on openlane/steps/step.py
> +        print(cmd_str, kwargs)
yes, good catch

2024-02-13 09:10 UTC, kareefardi approved these changes

2024-02-13 09:11 UTC, merged