Update OpenROAD
efabless/openlane2 pull request #472
Opened 2024-05-15 11:32 UTC by donn

## Tool Updates

* openroad -> a515fc6
  * Removed OpenLane-specific patch for querying existence of antenna information
  * `openroad-abc` -> `ef5389d`
    * `ABC_USE_NAMESPACE` now set, result injected into header file
  * `opensta` -> `ee8d3d0

---

Resolves #405 
Resolves #440

2024-06-02 14:49 UTC, donn commented
i hate you openlane bot

2024-06-04 07:49 UTC, kareefardi requested changes
There is a design with a new hold violation

2024-06-04 15:03 UTC, donn commented
I was too lazy to update the design's config so I decided to update OpenROAD instead

2024-06-05 07:59 UTC, donn commented
i think this is one of those nondeterministic bugs bec the hold violation isn't there on macOS so that's fun

2024-06-12 11:14 UTC, merged