* `OpenROAD.STA*PNR`
efabless/openlane2 pull request #535
Opened 2024-08-22 07:30 UTC by donn

* New environment variable made accessible to SDC files used during Multi-Corner STA steps, `OPENLANE_SDC_IDEAL_CLOCKS`, set to `1` for pre-PnR. Band-aid until the SDC situation is properly discussed and addressed (in a potentially breaking change.)
  * Fixed issue where the clock was always propagated after `STAPrePNR` regardless the information in the SDC file.
  * For backwards compatibility, `STAPrePNR` unsets all propagated clocks and the rest set all propagated clocks IF the SDC file lacks the strings `set_propagated_clock` or `unset_propagated_clock`.

2024-08-27 10:43 UTC, kareefardi requested changes
`OPENLANE_SDC_IDEAL_CLOCKS` is an internal variable. It should be prefixed with `_` (or `__`?)

2024-08-27 11:51 UTC, donn commented
It is not an internal variable. It is a variable exposed to SDC files.

What I can do is add it to the step documentation.

2024-08-27 11:56 UTC, donn commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        into the step directory, then typing `openlane.steps create-reproducible`
no

2024-08-27 12:34 UTC, kareefardi commented
> It is not an internal variable. It is a variable exposed to SDC files.
> 
> What I can do is add it to the step documentation.

Isn't it forced to specific value in some steps?

2024-09-02 09:22 UTC, kareefardi approved these changes

2024-09-02 09:22 UTC, kareefardi commented
I think users may miss `OPENLANE_SDC_IDEAL_CLOCKS` but since it is getting removed in OpenLane 3 perhaps it is not that big of a deal.

2024-09-09 08:04 UTC, kareefardi approved these changes

2024-09-10 12:41 UTC, merged